#!/bin/sh
#
# Executed by startx (run your window manager from here).
# shellcheck disable=SC1090
# shellcheck disable=SC1091

# Tell the state of the battery.
bat_state() {
    upower -i /org/freedesktop/UPower/devices/battery_BAT0 \
        | grep state | awk '{ print $2 }'
}

# Import various system-wide snippets.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
	    [ -x "$f" ] && . "$f"
    done
    unset f
fi

cd ~ || exit

# Mute the microphone.
pulseaudio-ctl mute-input

# Set the brightness according to the battery state.
if [ "$(bat_state)" = "discharging" ]; then
    xbacklight -set 20
    pactl set-sink-mute 0 toggle
else
    xbacklight -set 60
fi

# Turn off the bell.
xset -b

# Set the key press auto-repeat for the X environment.
xset r rate 330 25

# Load sh/bash global environment.
[ -f ~/.config/sh/environ ] && . ~/.config/sh/environ

# Load global profiles.
[ -f /etc/profile ] && . /etc/profile
[ -f ~/.config/sh/profile ] && . ~/.config/sh/profile

# Load X11 resources.
[ -f "$XDG_CONFIG_HOME/X11/Xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"

setxkbmap us_qwerty-fr

# Start graphical server if there is not already a session running on TTY1.
if [ "$(tty)" = "/dev/tty1" ]; then
    pgrep -x i3 || exec ssh-agent i3
fi
