#!/bin/sh
#
# X11-specific login script (after ~/.profile).

have() { type "$1" > /dev/null 2>&1; }

if have compton; then
    if [ -f ~/.config/compton/compton.conf ]; then
	compton --config ~/.config/compton/compton.conf &
    else
	compton &
    fi
fi

if have dunst; then
    dunst &
fi

if have emacs; then
    emacs --daemon &
fi

if have mpd; then
    [ ! -s ~/.config/mpd/pid ] && mpd &
fi

if have syncthing; then
    syncthing -no-browser &
fi

if have unclutter; then
    unclutter --ignore-scrolling --jitter 2 &
fi

if have xbindkeys; then
    xbindkeys -f "$XDG_CONFIG_HOME/X11/xbindkeysrc" &
fi
