#!/bin/sh
#
# Load aliases and functions

# Avoid weird aliases on public shell servers.
unalias -a

# Generate an SSH key dynamically in the correct directory.
gen() {
    if [ ! -z "$1" ]; then
	ssh-keygen -t rsa -b 4096 -C $EMAIL -f "$XDG_DATA_HOME/ssh/keys/$1"
    else
	echo "You must provide a file name"
    fi
}

# Verify that a package is installed.
have() { type "$1" > /dev/null 2>&1; }

# Alias respecting programs.
alias electrum='electrum --dir $XDG_CONFIG_HOME/electrum'
alias mbsync='mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc'
alias newsboat='newsboat -u $XDG_CONFIG_HOME/newsboat/urls'
alias ssh='ssh -F $XDG_CONFIG_HOME/ssh/config'
alias startx='startx $XDG_CONFIG_HOME/X11/xinitrc'
alias tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf'

# Convertions
if have libreoffice-fresh; then
    alias doc2pdf='libreoffice --headless --convert-to pdf *.docx'
    alias odt2pdf='libreoffice --headless --convert-to pdf *.odt'
fi

# Battery
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state|to\ full|percentage"'

# Display
alias ls='ls --color=auto'

# Docker
if have docker; then
    alias dke='docker exec -it'
    alias dkr='docker run -d -P --name'
fi

alias moc='mu cfind --format=org-contact'

# GNU Emacs
if have emacs; then
    alias ec="emacsclient -a '' -t"
fi

# GPG
alias gpgC='gpg --recipient \$GPGKEY --encrypt'
alias gpgDP='gpg --delete-keys'
alias gpgDS='gpg --delete-secret-keys'
alias gpgE='gpg --edit-key'
alias gpgG='gpg --full-generate-key'
alias gpgLP='gpg --list-keys'
alias gpgLS='gpg -K'
alias gpgR='gpg-connect-agent reloadagent /bye'

# LaTeX
alias xelatex='xelatex --shell-escape'

# Navigation
alias d='cd $XDG_DATA_HOME/docker/'
alias g='cd $XDG_DATA_HOME/git/'
alias q='cd $XDG_DATA_HOME/qemu/'

# nmcli
alias list_wifi='nmcli device wifi list'

# pacman
alias inpac='pacman -Qmq | sort'
alias mymakepkg='makepkg -sirc'

# qutebrowser
alias qutebrowser='rm ~/.local/share/qutebrowser/history.sqlite && qutebrowser'

# NNN
alias n='nnn'

# systemctl
alias services='systemctl list-unit-files | grep enabled && systemctl --user list-unit-files | grep enabled'

# top
alias top_cpu='top -b -o +%CPU | head -n 22'
alias top_mem='top -b -o +%MEM | head -n 22'

# tmux
alias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias tk='tmux kill-session -t'
alias tka='tmux kill-server'
alias tl='tmux list-sessions'
alias ts='tmux new-session -s'

# Traduction
if have trans; then
    alias de='trans --brief :de'
    alias en='trans --brief :en'
    alias fr='trans --brief :fr'
    alias it='trans --brief :it'
    alias nl='trans --brief :nl'
fi

# youtube-dl
if have youtube-dl; then
    alias yeam='youtube-dl --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 -o "~/Music/%(title)s.%(ext)s"'
fi
