#!/bin/sh

# Avoid weird aliases on public shell servers.
unalias -a

have() { type "$1" > /dev/null 2>&1; }

# Alias respecting programs.
alias electrum="electrum --dir $XDG_CONFIG_HOME/electrum"
alias mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc"
alias newsboat="newsboat -u $XDG_DATA_HOME/newsboat/urls"
alias ssh="ssh -F $XDG_CONFIG_HOME/ssh/config"
alias startx="startx $XDG_CONFIG_HOME/X11/xinitrc"
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"

# Convertions
if have libreoffice-fresh; then
    alias doc2pdf="libreoffice --headless --convert-to pdf *.docx"
    alias odt2pdf="libreoffice --headless --convert-to pdf *.odt"
fi

# Battery
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage"'

# Display
alias ls='ls --color=auto'

# Docker
if have docker; then
    alias dke="docker exec -it $1 sh"
    alias dkr="docker run -d -P --name $1 $2"
fi

# GNU Emacs
if have emacs; then
    alias ec="emacsclient -a '' -t"
fi

alias moc="mu cfind --format=org-contact"

# GPG
alias gpgC="gpg --recipient \$GPGKEY --encrypt"
alias gpgDP="gpg --delete-keys"
alias gpgDS="gpg --delete-secret-keys"
alias gpgE="gpg --edit-key"
alias gpgG="gpg --full-generate-key"
alias gpgLP="gpg --list-keys"
alias gpgLS="gpg -K"
alias gpgR="gpg-connect-agent reloadagent /bye"

# LaTeX
alias xelatex="xelatex --shell-escape"

# Navigation
alias gD="cd ~/Downloads/"
alias gde="cd ~/Desktop/"
alias gdo="cd ~/Documents"
alias gp="cd ~/Pictures/"
alias gw="cd ~/Pictures/Wallpapers/2560x1440/"
alias gW="cd ~/Pictures/Wallpapers/"

# nmcli
alias list_wifi="nmcli device wifi list"

# pacman
alias inpac="pacman -Qmq | sort"
alias mymakepkg="makepkg -sirc"

# systemctl
alias services="systemctl list-unit-files | grep enabled && systemctl --user list-unit-files | grep enabled"
# top
alias top_mem="top -b -o +%MEM | head -n 22"
alias top_cpu="top -b -o +%MEM | head -n 22"

# Traduction
if have trans; then
    alias de="trans --brief :de"
    alias en="trans --brief :en"
    alias fr="trans --brief :fr"
    alias it="trans --brief :it"
    alias nl="trans --brief :nl"
fi

# youtube-dl
if have youtube-dl; then
    alias yeam="youtube-dl --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 -o '~/Music/%(title)s.%(ext)s'"
fi
