#!/bin/sh
#
# Executed by login shells.
# Not read by bash(1), if ~/.bash_profile or ~/.bash_login exists.

# Cache directory for Ccache.
export CCACHE_DIR="$XDG_CACHE_DIR/ccache"
# Tells Ccache to only use compilers in this directory.
export CCACHE_PATH="/usr/bin"

# Use emacsclient as default text editor.
export EDITOR="emacsclient -a '' -t"

# Useful to inform Polybar of GitHub's token.
GITHUB_ACCESS_TOKEN="$(gpg -qd "$HOME/.gnupg/shared/.github-token.gpg")"
export GITHUB_ACCESS_TOKEN

# Identify the private key.
GPGKEY="$(gpg -K | awk 'NR==4 {print $1}' | sed 's/4096R\///g')"
export GPGKEY

# Used by gpg-agent.
GPG_TTY="$(tty)"
export GPG_TTY

# Related to Java.
export JAVA_HOME="/usr/lib/jvm/default-runtime"
export JDK_HOME="/usr/lib/jvm/default"

# Prevent `less` from storing the history.
export LESSHISTFILE="-"

# Disable warning for GTK-based applications.
export NO_AT_BRIDGE=1

# Set length of passwords generated by pass.
export PASSWORD_STORE_GENERATED_LENGTH=50

# Allows you to use $HOME/bin's bash scripts anywhere.
if [ -d "$HOME/bin" ]; then
    export PATH="$PATH:$HOME/bin"
fi

# Loads the specified modules and other codes when Python starts.
export PYTHONSTARTUP="$HOME/.pythonrc"

# Tell the Shell used by default.
export SHELL=${SHELL:-/bin/bash}

# Use termite as default terminal.
export TERMINAL="termite"

# Add temporary files according to the user.
export TMPDIR="/tmp/$USER"
if [ ! -d "$TMPDIR" ]; then
    mkdir -m 700 "$TMPDIR"
fi

# Create extra folders for XDG.
export XDG_CACHE_DIR="$HOME/.cache"
export XDG_CONFIG_DIR="$HOME/.config"
export XDG_DATA_DIR="$HOME/.local/share"

mkdir -p "$XDG_CACHE_DIR" "$XDG_CONFIG_DIR" "$XDG_DATA_DIR"

# Path to the oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Start graphical server if i3 is not already running on TTY1.
if [ "$(tty)" = "/dev/tty1" ]; then
    pgrep -x i3 || exec startx
fi

# Start graphical server if sway is not already running on TTY2.
if [ "$(tty)" = "/dev/tty2" ]; then
    pgrep -x sway || exec sway

    export XKB_DEFAULT_LAYOUT=us
    export XKB_DEFAULT_OPTIONS=caps:escape
    export XKB_DEFAULT_VARIANT=intl
fi
