---
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Installs GNU Stow
        run: sudo apt-get install -y stow

      - name: Installs configuration files
        run: |
          ./stowsym.sh -i

      - name: Uninstalls configuration files
        run: |
          ./stowsym.sh -d
